[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "fc4253ed-5b58-4cdb-901f-f253d6244dc0"

# Settings in the [build] context are global and are applied to all contexts
[build]
  publish = "build/"
  command = "yarn build"

[context.production.environment]
  REACT_APP_API_URL = "https://cors-anywhere.herokuapp.com/https://cbrdoc.jhob.com.br"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://cors-anywhere.herokuapp.com/https://cbrdoc.jhob.com.br"

[context.staging.environment]
  REACT_APP_API_URL = "https://cors-anywhere.herokuapp.com/https://cbrdoc.jhob.com.br"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200